<?php declare(strict_types=1);

namespace App\Tests\Algorithm\Implementation\SortAlgorithms;

use App\Algorithm\Contracts\SortAlgorithmInterface;
use App\Algorithm\Implementation\SortAlgorithms\CountSortAlgorithm;
use App\Algorithm\Implementation\SortAlgorithms\InsertionSortAlgorithm;
use App\Utility\ArrayUtils;
use PHPUnit\Framework\TestCase;

class CountSortAlgorithmTest extends TestCase
{
    private ArrayUtils $arrayUtils;
    private SortAlgorithmInterface $sortAlgorithm;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->arrayUtils = new ArrayUtils();
        $this->sortAlgorithm = new CountSortAlgorithm();
    }

    public function testSortCorrectly()
    {
        $array = [5,5,2,5];

        $sorted = $this->sortAlgorithm->sort($array);

        $this->assertNotEquals($array, $sorted);

        foreach ($sorted as $key => $item) {
            $this->assertGreaterThanOrEqual($item, $sorted[$key + 1] ?? $item);
        }
    }
}
