<?php

namespace App\Tests\Algorithm\Implementation\SortAlgorithms;

use App\Algorithm\Contracts\SortAlgorithmInterface;
use App\Algorithm\Implementation\SortAlgorithms\InsertionSortAlgorithm;
use App\Utility\ArrayUtils;

class InsertionSortAlgorithmTest extends \PHPUnit\Framework\TestCase
{
    private ArrayUtils $arrayUtils;
    private SortAlgorithmInterface $sortAlgorithm;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->arrayUtils = new ArrayUtils();
        $this->sortAlgorithm = new InsertionSortAlgorithm();
    }

    public function testSortCorrectly()
    {
        $array = $this->arrayUtils->getRandomized();

        $sorted = $this->sortAlgorithm->sort($array);

        $this->assertNotEquals($array, $sorted);

        foreach ($sorted as $key => $item) {
            $this->assertGreaterThanOrEqual($item, $sorted[$key + 1] ?? $item);
        }
    }
}